services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  elfexporter:
    image: yongenaelf/elfexporter
    environment:
      - AELF_URL=https://tdvw-test-node.aelf.io
      - PORT=8080
      - PREFIX=
      - SLEEP_DURATION=15
    volumes:
      - ./addresses.txt:/addresses.txt
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - "9093:9093"
  lark-webhook:
    image: ghcr.io/yongenaelf/lark-alertmanager-webhook:sha-4b4e41b
    volumes:
      - ./lark.yml:/app/config/config.yaml
      
volumes:
  prom_data:
